[options]
; This is the password that allows database operations:
addons_path = /mnt/extra-addons,/mnt/custom-addons
admin_passwd = zktIA3nYB
db_host = 172.18.0.1
db_port = 5432
db_user = erp18
db_password = kkHOzy0T7hfl
xmlrpc_port = 8069
proxy_mode = True
;workers = 2
;max_cron_threads = 1
;gevent_port = 8072