# Rate limiting zones
limit_req_zone $binary_remote_addr zone=login_limit:10m rate=5r/m;
limit_req_zone $binary_remote_addr zone=general:10m rate=30r/s;

# Block IPs
geo $block_ip {
    default           0;
    94.154.43.105     1;
    83.70.174.134     1;
    20.219.185.206    1;
}

# Block user agents
map $http_user_agent $block_agent {
    default           0;
    ~*nikto           1;
    ~*sqlmap          1;
    ~*Go-http-client  1;
    ~*python-requests 1;
}

# Fix proxy headers hash warning
proxy_headers_hash_max_size 1024;
proxy_headers_hash_bucket_size 128;